// <auto-generated />
using System;
using Infrastructure.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthcareSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<int?>("ConsultantId")
                        .HasColumnType("int")
                        .HasColumnName("ConsultantID");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<string>("MeetLink")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("MemberID");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Symptoms")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentId")
                        .HasName("PK__Appointm__8ECDFCA2D172AD9E");

                    b.HasIndex("ConsultantId");

                    b.HasIndex("MemberId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BlogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"));

                    b.Property<int?>("ConsultantId")
                        .HasColumnType("int")
                        .HasColumnName("ConsultantID");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("PublishDate")
                        .HasColumnType("date");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Topic")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BlogId")
                        .HasName("PK__Blog__54379E5044619794");

                    b.HasIndex("ConsultantId");

                    b.ToTable("Blog", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.BlogImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ImageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<int?>("BlogId")
                        .HasColumnType("int")
                        .HasColumnName("BlogID");

                    b.Property<string>("ImageCaption")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UploadDate")
                        .HasColumnType("datetime");

                    b.HasKey("ImageId")
                        .HasName("PK__BlogImag__7516F4EC111C0B4F");

                    b.HasIndex("BlogId");

                    b.ToTable("BlogImage", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.BlogView", b =>
                {
                    b.Property<int>("BlogViewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BlogViewID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogViewId"));

                    b.Property<int?>("BlogId")
                        .HasColumnType("int")
                        .HasColumnName("BlogID");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("MemberID");

                    b.Property<DateTime?>("ViewDate")
                        .HasColumnType("datetime");

                    b.HasKey("BlogViewId")
                        .HasName("PK__BlogView__5A5F0B6CFF67BCB5");

                    b.HasIndex("BlogId");

                    b.HasIndex("MemberId");

                    b.ToTable("BlogView", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FeedbackID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FeedbackDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("RecordId")
                        .HasColumnType("int")
                        .HasColumnName("RecordID");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Feedback__6A4BEDF62A9CAF58");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("RecordId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InvoiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TaxRate")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("TestServiceRecordId")
                        .HasColumnType("int")
                        .HasColumnName("TestServiceRecordID");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UnitPrice")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("InvoiceId")
                        .HasName("PK__Invoice__D796AAD50B806764");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("TestServiceRecordId");

                    b.ToTable("Invoice", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("IsRead");

                    b.Property<DateTime?>("SendTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E325DAFA885");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OtpRequest", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OTPID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtpId"));

                    b.Property<string>("Code")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("IsVerified")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("OtpId")
                        .HasName("PK__OTPReque__5C2EC562B070925E");

                    b.HasIndex("UserId");

                    b.ToTable("OTPRequest", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QuestionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("AnsCount")
                        .HasColumnType("int");

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ConsultantId")
                        .HasColumnType("int")
                        .HasColumnName("ConsultantID");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Heart")
                        .HasColumnType("bit");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("MemberID");

                    b.Property<int?>("SpecialtyId")
                        .HasColumnType("int")
                        .HasColumnName("SpecialtyId");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("SubmitDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TitleQuestion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("QuestionId")
                        .HasName("PK__Question__0DC06F8C7085B3FF");

                    b.HasIndex("ConsultantId");

                    b.HasIndex("MemberId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.QuestionThreadItem", b =>
                {
                    b.Property<int>("ThreadItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ThreadItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThreadItemId"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("datetime");

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsAnswered")
                        .HasColumnType("bit");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("QuestionID");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime");

                    b.HasKey("ThreadItemId")
                        .HasName("PK__QuestionThreadItem");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionThreadItem", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReportServiceDetail", b =>
                {
                    b.Property<int>("ReportServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReportServiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportServiceId"));

                    b.Property<decimal?>("AvgRating")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("ReportPeriod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<decimal?>("TotalRevenue")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("ReportServiceId")
                        .HasName("PK__ReportSe__EBE898635120F25D");

                    b.HasIndex("ServiceId");

                    b.ToTable("ReportServiceDetail", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReproductiveCycle", b =>
                {
                    b.Property<int>("CycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CycleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CycleId"));

                    b.Property<int?>("CycleLength")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime");

                    b.Property<int>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("MemberID");

                    b.Property<int?>("PeriodLength")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("PillTime")
                        .HasColumnType("time");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("CycleId")
                        .HasName("PK__Reproduc__077B24D97C9AA5A6");

                    b.HasIndex("MemberId");

                    b.ToTable("ReproductiveCycle", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("RoleID");

                    b.Property<string>("RoleDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE3A872501E5");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ServiceId")
                        .HasName("PK__Service__C51BB0EA63AB2E89");

                    b.ToTable("Service", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Specialty", b =>
                {
                    b.Property<int>("SpecialtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SpecialtyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecialtyId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SpecialtyId")
                        .HasName("PK__Specialt__D768F6489A0BBC10");

                    b.ToTable("Specialty", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TestServiceRecord", b =>
                {
                    b.Property<int>("TestServiceRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TestServiceRecordID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestServiceRecordId"));

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("FullNameOfMember")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("MemberID");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime?>("RecordDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Result")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("TestDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("TimeSlot")
                        .HasColumnType("TIME");

                    b.HasKey("TestServiceRecordId")
                        .HasName("PK__TestServ__F810175D4779B45B");

                    b.HasIndex("MemberId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StaffId");

                    b.ToTable("TestServiceRecord", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Avatar")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateOnly?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("DoB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("RoleID");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CCAC907AF080");

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.WeeklyOverrideSchedule", b =>
                {
                    b.Property<int>("WeeklyOverrideScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeeklyOverrideScheduleId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("OverrideType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShiftType")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WeeklyOverrideScheduleId");

                    b.HasIndex("UserId");

                    b.ToTable("WeeklyOverrideSchedules");
                });

            modelBuilder.Entity("Domain.Entities.WeeklySchedule", b =>
                {
                    b.Property<int>("WeeklyScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeeklyScheduleId"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TIME");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShiftType")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TIME");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WeeklyScheduleId");

                    b.HasIndex("UserId");

                    b.ToTable("WeeklySchedules");
                });

            modelBuilder.Entity("UserSpecialty", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int")
                        .HasColumnName("SpecialtyID");

                    b.HasKey("UserId", "SpecialtyId")
                        .HasName("PK__UserSpec__8AFE43C8943BFACE");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("UserSpecialty", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Domain.Entities.User", "Consultant")
                        .WithMany("AppointmentConsultants")
                        .HasForeignKey("ConsultantId")
                        .HasConstraintName("FK__Appointme__Consu__3F466844");

                    b.HasOne("Domain.Entities.User", "Member")
                        .WithMany("AppointmentMembers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Appointme__Membe__3D5E1FD2");

                    b.HasOne("Domain.Entities.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK__Appointme__Servi__3E52440B");

                    b.Navigation("Consultant");

                    b.Navigation("Member");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Domain.Entities.Blog", b =>
                {
                    b.HasOne("Domain.Entities.User", "Consultant")
                        .WithMany("Blogs")
                        .HasForeignKey("ConsultantId")
                        .HasConstraintName("FK__Blog__Consultant__34C8D9D1");

                    b.Navigation("Consultant");
                });

            modelBuilder.Entity("Domain.Entities.BlogImage", b =>
                {
                    b.HasOne("Domain.Entities.Blog", "Blog")
                        .WithMany("BlogImages")
                        .HasForeignKey("BlogId")
                        .HasConstraintName("FK__BlogImage__BlogI__59063A47");

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("Domain.Entities.BlogView", b =>
                {
                    b.HasOne("Domain.Entities.Blog", "Blog")
                        .WithMany("BlogViews")
                        .HasForeignKey("BlogId")
                        .HasConstraintName("FK__BlogView__BlogID__5CD6CB2B");

                    b.HasOne("Domain.Entities.User", "Member")
                        .WithMany("BlogViews")
                        .HasForeignKey("MemberId")
                        .HasConstraintName("FK__BlogView__Member__5BE2A6F2");

                    b.Navigation("Blog");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Domain.Entities.Feedback", b =>
                {
                    b.HasOne("Domain.Entities.Appointment", "Appointment")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AppointmentId")
                        .HasConstraintName("FK__Feedback__Appoin__656C112C");

                    b.HasOne("Domain.Entities.TestServiceRecord", "Record")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RecordId")
                        .HasConstraintName("FK__Feedback__Record__66603565");

                    b.Navigation("Appointment");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("Domain.Entities.Invoice", b =>
                {
                    b.HasOne("Domain.Entities.Appointment", "Appointment")
                        .WithMany("Invoices")
                        .HasForeignKey("AppointmentId")
                        .HasConstraintName("FK__Invoice__Appoint__5441852A");

                    b.HasOne("Domain.Entities.TestServiceRecord", "TestServiceRecord")
                        .WithMany("Invoices")
                        .HasForeignKey("TestServiceRecordId")
                        .HasConstraintName("FK__Invoice__TestSer__5535A963");

                    b.Navigation("Appointment");

                    b.Navigation("TestServiceRecord");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Notificat__UserI__4BAC3F29");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.OtpRequest", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("OtpRequests")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__OTPReques__UserI__48CFD27E");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.HasOne("Domain.Entities.User", "Consultant")
                        .WithMany("QuestionConsultants")
                        .HasForeignKey("ConsultantId")
                        .HasConstraintName("FK__Question__Consul__45F365D3");

                    b.HasOne("Domain.Entities.User", "Member")
                        .WithMany("QuestionMembers")
                        .HasForeignKey("MemberId")
                        .HasConstraintName("FK__Question__Member__44FF419A");

                    b.HasOne("Domain.Entities.Specialty", "Specialty")
                        .WithMany("Questions")
                        .HasForeignKey("SpecialtyId");

                    b.Navigation("Consultant");

                    b.Navigation("Member");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Domain.Entities.QuestionThreadItem", b =>
                {
                    b.HasOne("Domain.Entities.Question", "Question")
                        .WithMany("QuestionThreadItems")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("FK__QuestionThreadItem__Question");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Entities.ReportServiceDetail", b =>
                {
                    b.HasOne("Domain.Entities.Service", "Service")
                        .WithMany("ReportServiceDetails")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK__ReportSer__Servi__4222D4EF");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Domain.Entities.ReproductiveCycle", b =>
                {
                    b.HasOne("Domain.Entities.User", "Member")
                        .WithMany("ReproductiveCycles")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Reproduct__Membe__2F10007B");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Domain.Entities.TestServiceRecord", b =>
                {
                    b.HasOne("Domain.Entities.User", "Member")
                        .WithMany("TestServiceRecordMembers")
                        .HasForeignKey("MemberId")
                        .HasConstraintName("FK__TestServi__Membe__398D8EEE");

                    b.HasOne("Domain.Entities.Service", "Service")
                        .WithMany("TestServiceRecords")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK__TestServi__Servi__38996AB5");

                    b.HasOne("Domain.Entities.User", "Staff")
                        .WithMany("TestServiceRecordStaffs")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK__TestServi__Staff__3A81B327");

                    b.Navigation("Member");

                    b.Navigation("Service");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__User__RoleID__286302EC");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.WeeklyOverrideSchedule", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("WeeklyOverrideSchedules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.WeeklySchedule", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("WeeklySchedules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserSpecialty", b =>
                {
                    b.HasOne("Domain.Entities.Specialty", null)
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .IsRequired()
                        .HasConstraintName("FK__UserSpeci__Speci__4F7CD00D");

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserSpeci__UserI__4E88ABD4");
                });

            modelBuilder.Entity("Domain.Entities.Appointment", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Domain.Entities.Blog", b =>
                {
                    b.Navigation("BlogImages");

                    b.Navigation("BlogViews");
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.Navigation("QuestionThreadItems");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Service", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ReportServiceDetails");

                    b.Navigation("TestServiceRecords");
                });

            modelBuilder.Entity("Domain.Entities.Specialty", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Domain.Entities.TestServiceRecord", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("AppointmentConsultants");

                    b.Navigation("AppointmentMembers");

                    b.Navigation("BlogViews");

                    b.Navigation("Blogs");

                    b.Navigation("Notifications");

                    b.Navigation("OtpRequests");

                    b.Navigation("QuestionConsultants");

                    b.Navigation("QuestionMembers");

                    b.Navigation("ReproductiveCycles");

                    b.Navigation("TestServiceRecordMembers");

                    b.Navigation("TestServiceRecordStaffs");

                    b.Navigation("WeeklyOverrideSchedules");

                    b.Navigation("WeeklySchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
